### PR TITLE
Fix: #274

### PR DESCRIPTION
**Pull request by PinkPenguin418**
## Problem

Issue with saving a custom store. Would get an error thrown.

## Solution

Needed to rename custom store save data variable to improve readability. Also needed to initialize the custom store in the original saveData variable. Created a condition to limit the creation to only once and only if there are custom stores with save functionality.

### CODE REVIEW

**Review by liana-p — APPROVED** [review]
I wonder why it's undefined... but this should work

**Comment by PinkPenguin418** [comment]
Doesn't look like it passed the CI build. Are you able to see what's breaking?

**Comment by liana-p** [comment]
> Doesn't look like it passed the CI build. Are you able to see what's breaking?

just merged when you said that lol. Yeah I looked at it and it's a problem with pnpm versions in CI, I need to change something in config files because it breaks every time there's an update, so for now I just merged this PR anyway

**Comment by PinkPenguin418** [comment]
Thanks Liana. This is the first time I contribute to a public repo, so still learning how it all works.

**Comment by PinkPenguin418** [comment]
I tried downloading the latest narrat and it doesn't look like the fix is there yet. I'm not sure if I'm doing something wrong or you just haven't published yet.

**Pull request merged**
